language: rust

matrix:
    include:
        - rust: stable
        - rust: beta
        - rust: nightly
          name: "Rust: nightly"

        - rust: stable
          name: clippy
          before_script:
            - rustup component add clippy
          script:
            - cargo clippy

        - rust: nightly
          name: rustfmt
          before_script:
            - rustup component add rustfmt
          script:
            - cargo fmt -- --check

script:
    - cargo build
    - cargo test
