language: rust

matrix:
    include:
        - rust: stable
        - rust: beta
        - rust: nightly

        - rust: stable
          name: clippy
          before_script:
            - rustup component add clippy
          script:
            - cargo clippy

        - rust: nightly
          name: rustfmt
          before_script:
            - rustup component add rustfmt
          script:
            - cargo fmt -- --check
        - rust: stable
          name: hello-world
          script:
            make

jobs:
    include:
        - stage: build
          name: "Build app"
          script: cargo build

        - stage: test
          name: "Unit tests"
          script: cargo test
